version: '3'
services:
  ###################
  # back postgres
  ###################
  db:
    container_name: cashmanager_db
    image: mariadb:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: cashmanager
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  ###################
  # tomcat server
  ###################
  web:
    container_name: cashmanager_tomcat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      HOST: 0.0.0.0
    depends_on:
      - db
    links:
      - db 