package dao;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Map;

import exception.NoResultException;
import tables.TableClass;
import utils.CM_Log;
import utils.DBConnector;
import utils.ErrorsHandler;

public abstract class Dao {
	DBConnector db;
	ErrorsHandler errorHandler;
	
	public Dao(DBConnector db, ErrorsHandler errorHandler) {
		this.db = db;
		this.errorHandler = errorHandler;
	}
	
	//===================================================================================
    /*
     * 
     */
    public boolean add(TableClass entityClass) throws NoResultException, SQLException {
    	long id = db.executePreparedSQL(
													"INSERT INTO " + entityClass.getTable().getName() +" (" + entityClass.getTable().getFields() + ") " +
													"VALUES (" + entityClass.getTable().getFieldsPrepared() + ");",
													true,
													entityClass.getFieldsValues()
												);
		boolean res = id  > 0;
		if(entityClass.getTable().hasAutoGeneratedField())
			entityClass.setEntityID(id);
		CM_Log.debug("Insert " + (res ? "success" : "error") + " in " + entityClass.getTable().getName());
		
		return res;
    }

    
    //===================================================================================
    /*
     * 
     */
    public boolean update(TableClass entityClass) throws NoResultException, SQLException {
    	boolean res = db.executePreparedSQL(
														"UPDATE " + entityClass.getTable().getName() + " " +
														"SET " + entityClass.getTable().getSetFields() + " " +
														"WHERE " + entityClass.getTable().getSetID() + ";",
														false,
														addArrayElem(entityClass.getFieldsValues(), entityClass.getEntityID())
													) > 0;

		CM_Log.debug("Update " + (res ? "success" : "error") + " in " + entityClass.getTable().getName());
		return res;
    }
    //------------------------------------------------------------
    private Object[] addArrayElem(Object[] arr, Object elem) {
    	Object[] newArray = new Object[arr.length+1];
        System.arraycopy(arr, 0, newArray, 0, arr.length);
        newArray[arr.length] = elem;
    	return newArray;
    }
    

    //===================================================================================
    /*
     * 
     */
    public boolean delete(TableClass entityClass) throws NoResultException, SQLException {
    	boolean res = db.executePreparedSQL(
														"DELETE FROM " + entityClass.getTable().getName() +" " +
														"WHERE " + entityClass.getTable().getSetID() + ";",
														false,
														new Object[]{entityClass.getEntityID()}
													) > 0;
				
		CM_Log.debug("Delete " + (res ? "success" : "error") + " in " + entityClass.getTable().getName());
		return res;
	}
        
    //===================================================================================
    /*
     * 
     */
    protected ArrayList<Map<String, Object>> query(String queryString, Object[] values) throws SQLException {
  		return db.executeQuerySQL(queryString, values);
    }
    //------------------------------------------------------------
    protected ArrayList<Map<String, Object>> query(String queryString) throws SQLException {
    	return query(queryString, new Object[]{});
    }
}
