package dao;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Map;

import entities.EntityClass;
import exception.NoResultException;
import utils.DBConnector;
import utils.ErrorsHandler;

public abstract class Dao {
	DBConnector db;
	ErrorsHandler errorHandler;
	
	public Dao(DBConnector db, ErrorsHandler errorHandler) {
		this.db = db;
		this.errorHandler = errorHandler;
	}
	
	//===================================================================================
    /*
     * 
     */
    public boolean add(EntityClass entityClass) throws NoResultException, SQLException {
    	long id = db.executePreparedSQL(
													"INSERT INTO " + entityClass.table().getName() +" (" + entityClass.table().getFields() + ") " +
													"VALUES (" + entityClass.table().getFieldsPrepared() + ");",
													entityClass.table().hasAutoGeneratedField(),
													entityClass.fieldsValues()
												);
		boolean res = id  > 0;
		if(entityClass.table().hasAutoGeneratedField())
			entityClass.setId(id);
		errorHandler.addDebug("Insert " + (res ? "success" : "error") + " in " + entityClass.table().getName() + " | result: " + id);
		
		return res;
    }

    
    //===================================================================================
    /*
     * 
     */
    public boolean update(EntityClass entityClass) throws NoResultException, SQLException {
    	boolean res = db.executePreparedSQL(
														"UPDATE " + entityClass.table().getName() + " " +
														"SET " + entityClass.table().getFieldsSet() + " " +
														"WHERE " + entityClass.table().getIDSet() + ";",
														false,
														addArrayElem(entityClass.fieldsValues(), entityClass.getId())
													) > 0;

		errorHandler.addDebug("Update " + (res ? "success" : "error") + " in " + entityClass.table().getName());
		return res;
    }
    //------------------------------------------------------------
    private Object[] addArrayElem(Object[] arr, Object elem) {
    	Object[] newArray = new Object[arr.length+1];
        System.arraycopy(arr, 0, newArray, 0, arr.length);
        newArray[arr.length] = elem;
    	return newArray;
    }
    

    //===================================================================================
    /*
     * 
     */
    public boolean delete(EntityClass entityClass) throws NoResultException, SQLException {
    	boolean res = db.executePreparedSQL(
														"DELETE FROM " + entityClass.table().getName() +" " +
														"WHERE " + entityClass.table().getIDSet() + ";",
														false,
														new Object[]{entityClass.getId()}
													) > 0;
				
		errorHandler.addDebug("Delete " + (res ? "success" : "error") + " in " + entityClass.table().getName());
		return res;
	}
        
    //===================================================================================
    /*
     * 
     */
    protected ArrayList<Map<String, Object>> query(String queryString, Object[] values) throws SQLException {
  		return db.executeQuerySQL(queryString, values);
    }
    //------------------------------------------------------------
    protected ArrayList<Map<String, Object>> query(String queryString) throws SQLException {
    	return query(queryString, new Object[]{});
    }
}
