package utils;


public class Table {
	private String name;
	private TableFields[] fields;
	
	public Table(String name, TableFields[] fields) {
		this.name = name;
		this.fields = fields;
	}
	
	public boolean hasAutoGeneratedField() {
		for(int i = 0; i < fields.length; i++)
			if(fields[i].isAutoGenerated())
				return true;
		return false;
	}
	
	public String getName() {
		return this.name;
	}
	
	public String getFieldsPrepared() {
		String res = "";
		for(int i = 0; i < fields.length; i++)
			if(!(fields[i].getKeyType() == TableFields.KEY_PRIMARY && fields[i].getType() == TableFields.TYPE_INT ))
				res += (res == "" ? "" : ", ") + "?";
		return res;
	}
	
	public String getFields() {
		String res = "";
		for(int i = 0; i < fields.length; i++)
			if(!(fields[i].getKeyType() == TableFields.KEY_PRIMARY && fields[i].getType() == TableFields.TYPE_INT ))
				res += (res == "" ? "" : ", ") + fields[i].getName();
		return res;
	}
	
	public String getSetFields() {
		String res = "";
		for(int i = 0; i < fields.length; i++)
			if(!(fields[i].getKeyType() == TableFields.KEY_PRIMARY && fields[i].getType() == TableFields.TYPE_INT ))
				res += (res == "" ? "" : ", ") + fields[i].getPreparedField();
		return res;
	}
	
	public String getSetID() {
		String res = "";
		for(int i = 0; i < fields.length; i++)
			if(fields[i].getKeyType() == TableFields.KEY_PRIMARY)
				res += (res == "" ? "" : ", ") + fields[i].getPreparedField();
		return res;
	}
	
	public String getTableToSQL() {
		String res = "create table " + name + " (";
		for(int i = 0; i < fields.length; i++)
			res += (i < 1 ? "\n" : ", \n") + 	fields[i].getName() + " " +
												fields[i].getTypeString() + " " +
												(fields[i].getType() == TableFields.TYPE_INT &&
												 fields[i].getKeyType() == TableFields.KEY_PRIMARY ? "AUTO_INCREMENT " : " ") +
												(fields[i].getKeyType() == TableFields.KEY_PRIMARY ? "PRIMARY KEY " : " ") +
												"not null";
		
		res += "\n)";
		
		return res;
	}
}